<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <ProjectType>Local</ProjectType>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <AssemblyKeyContainerName>
    </AssemblyKeyContainerName>
    <AssemblyName>WindowsFormsSample</AssemblyName>
    <DefaultClientScript>JScript</DefaultClientScript>
    <DefaultHTMLPageLayout>Grid</DefaultHTMLPageLayout>
    <DefaultTargetSchema>IE50</DefaultTargetSchema>
    <DelaySign>false</DelaySign>
    <OutputType>WinExe</OutputType>
    <RootNamespace>WindowsFormsSample</RootNamespace>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <FileAlignment>4096</FileAlignment>
    <RegisterForComInterop>false</RegisterForComInterop>
    <RemoveIntegerChecks>false</RemoveIntegerChecks>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <FileAlignment>4096</FileAlignment>
    <RegisterForComInterop>false</RegisterForComInterop>
    <RemoveIntegerChecks>false</RemoveIntegerChecks>
    <DebugType>none</DebugType>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Platform)' == 'AnyCPU' ">
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="EmptyFirebirdDatabasePreparer.cs" />
    <Compile Remove="FirebirdEmbeddedPreparer.cs" />
    <Compile Remove="GridSamples\PingGrids\frmSample60.cs" />
    <Compile Remove="GridSamples\PingGrids\frmSample60.Designer.cs" />
    <Compile Remove="GridSamples\PingGrids\InsertRowsOperation.cs" />
    <Compile Remove="GridSamples\PingGrids\SessionFactoryManager.cs" />
    <Compile Remove="GridSamples\PingGrids\SessionManager.cs" />
    <Compile Remove="GridSamples\PingGrids\TransactionManager.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="GridSamples\PingGrids\frmSample60.resx" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Castle.Core">
      <HintPath>..\libs\Castle.Core.dll</HintPath>
    </Reference>
    <Reference Include="Castle.MicroKernel">
      <HintPath>..\libs\Castle.MicroKernel.dll</HintPath>
    </Reference>
    <Reference Include="Castle.Windsor">
      <HintPath>..\libs\Castle.Windsor.dll</HintPath>
    </Reference>
    <Reference Include="Esent.Collections">
      <HintPath>..\libs\Esent.Collections.dll</HintPath>
    </Reference>












    <Reference Update="System">
      <Name>System</Name>
    </Reference>
    <Reference Update="System.Data">
      <Name>System.Data</Name>
    </Reference>
    <Reference Update="System.Drawing">
      <Name>System.Drawing</Name>
    </Reference>
    <Reference Update="System.Xml">
      <Name>System.XML</Name>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="GridSamples\SampleData.xml" />
    <EmbeddedResource Include="GridSamples\SampleData2.xml" />
  </ItemGroup>
  <PropertyGroup>
    <RootNamespace>WindowsFormsSample</RootNamespace>
  </PropertyGroup>
	<PropertyGroup>
		<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
		<Version>1.0.0</Version>
		<AssemblyVersion>1.0.*</AssemblyVersion>
		<Deterministic>false</Deterministic>
	</PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SourceGrid.PingGrid.Backend.Essent\SourceGrid.PingGrid.Backend.Essent.csproj" />
    <ProjectReference Include="..\SourceGrid.PingGrid.Backends.DSet\SourceGrid.PingGrid.Backends.DSet.csproj" />
    <ProjectReference Include="..\SourceGrid\SourceGrid.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Condition="'$(TargetFramework)' == 'net48'" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
